### ISSUE TITLE
Testify suite tests not running

### ISSUE THREAD

**Issue by MathiasGr** [Microsoft/vscode-go#1968]
Starting from at least 0.6.90, tests bound to testify suites aren't detected by the vscode-go extension. Thus neither codelens or the "Test function at cursor" work anymore for this kind of test.

I also found a *second issue* while debugging the extension, which drove me crazy because it made the example suite from the [testify github page](https://github.com/stretchr/testify) work and show codelenses. The `testFuncRegex` is missing a `^` in front of `Example`, which makes the extension treat `(suite *ExampleTestSuite) TestExample()` like a regular test function, because it includes `Example`

Last, it should be documented somewhere that even with the fix in #1969 , users need to include `"go.gotoSymbol.includeImports": true` in their settings for testify to be properly detected.

Steps to Reproduce:
- Open vscode with the extension enabled and create a test file with the code below
- Try looking for codelenses and try "Test function at cursor"

```go
package example

import (
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/suite"
)

type Suite struct {
	suite.Suite
	VariableThatShouldStartAtFive int
}

func (suite *Suite) TestExample() {
	assert.Equal(suite.T(), 5, suite.VariableThatShouldStartAtFive)
}

func TestSuite(t *testing.T) {
	suite.Run(t, new(Suite))
}
```

Edit: fix for both issues in #1969

**Comment by ramya-rao-a** [comment]
Thanks for reporting @MathiasGr! And fixing it too :)

I have pushed your fix to master. Can you try out the [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension and confirm that the fix works?

**Comment by ramya-rao-a** [comment]
This is fixed in the latest update to the Go extension (0.6.91)

**Comment by mhr3** [comment]
Still having a problem with this, even with 0.6.91, does the fix only work with module-based projects or something like that?

**Comment by MathiasGr** [comment]
@mhr3 did you set the option `"go.gotoSymbol.includeImports": true ` ?

If you did, one issue might be that your suite is defined in another file, and `testify/suite` isn't imported in your test file. You can fix it by putting this line somewhere in your test file:
```go
var _ = suite.TestingSuite(nil)
```

**Comment by MathiasGr** [comment]
Well I'm afraid setting this setting `includeImports` to `true` is the only way to fix it right now.

**Comment by mhr3** [comment]
Sorry, missed that it's now *required* to set `includeImports` to true for this to work. And it indeed does after changing it.

**Comment by ramya-rao-a** [comment]
@mhr It is no _required_ to have that setting to have this feature to work. Its an unfortunate side effect of a refactoring I had done last week.

I have pushed a fix to master to take care of this. Can you try the latest [beta version]() of this extension? `testify` should be supported there with and without the `includeImports` setting.

**Comment by mhr3** [comment]
How do I get the beta? The link you posted points to this issue...

**Comment by ramya-rao-a** [comment]
@mhr3 Sorry about that! The link is updated.

**Comment by mhr3** [comment]
Thanks, and yep, works fine with the beta, even without `includeImports`.

**Comment by ramya-rao-a** [comment]
The fix is now out in the latest update to the Go extension (0.6.92)
