### ISSUE TITLE
Debugger not hitting breakpoints

### ISSUE THREAD

**Issue by olesiapoz** [Microsoft/vscode-go#2218]
I have the same issue as repoerted in #1987. Debugger not hitting break points. Breakpoint become "unverified" breakpoints during debug process.

Steps to Reproduce:

1. Steps dones as per debug go with Visual Studio Code.
2. Issue relevant to any go code.

**Comment by ramya-rao-a** [comment]
@olesiapoz Debugger not hitting break points can have multiple root causes. The instance reported in #1987 has been solved and I don't believe that is the same problem you are facing. Please go through [Debugging the debugger](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#debugging-the-debugger) section of our wiki and try out the various logging settings one by one. That might tell you what the issue is.

You can share the same here and I can help in figuring out what is happening.

Since you mentioned that this happens with any Go code, my guess is that this is some kind of environment issue. Please update your version of delve. Run `Go: Install/Update Tools`, select `dlv`, then press Ok to update

**Comment by ramya-rao-a** [comment]
Please follow the various logging features mentioned in [Debugging the debugger](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#debugging-the-debugger) and share the logs.

Are you using symlinks?

**Comment by olesiapoz** [comment]
Hello Ramya,

I have went through all suggestions Debugging the debugger
<https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#debugging-the-debugger>
and this did not solved an issues of debugging the solution. I have
structure, where my main.go file is in a root and api package with
endpoints.go files is within api directory (api/endpoints.go). I want to
debug endpoints.go. I do not use symlinks.

Here is my lunch config:
  "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceRoot}",
            "env": {"MONGO_HOST":"192.168.0.3:27017","USER_DATABASE":
"mongodb","GOPATH":"D:\\PhD\\Go\\"},
            "args": [],
            "trace": "verbose",
            "apiVersion": 2

        }
    ]
}


And here is debug output:

InitializeRequest
InitializeResponse
Using GOPATH: D:\PhD\Go\
Current working directory: D:\PhD\Go\src\serverless\user
Running: D:\PhD\Go\bin\dlv.exe debug serverless\user --headless=true
--listen=127.0.0.1:23931 --api-version=2 --
API server listening at: 127.0.0.1:23931
InitializeEvent
SetBreakPointsRequest
All cleared
Creating on: D:\PhD\Go\src\serverless\user\api\endpoints.go:18
Creating on: D:\PhD\Go\src\serverless\user\api\endpoints.go:74
Creating on: D:\PhD\Go\src\serverless\user\api\endpoints.go:75
Creating on: D:\PhD\Go\src\serverless\user\api\endpoints.go:79
Creating on: D:\PhD\Go\src\serverless\user\api\endpoints.go:81
Creating on: D:\PhD\Go\src\serverless\user\api\endpoints.go:84
Error on CreateBreakpoint: could not find
D:\PhD\Go\src\serverless\user\api\endpoints.go:18
Error on CreateBreakpoint: could not find
D:\PhD\Go\src\serverless\user\api\endpoints.go:74
Error on CreateBreakpoint: could not find
D:\PhD\Go\src\serverless\user\api\endpoints.go:75
Error on CreateBreakpoint: could not find
D:\PhD\Go\src\serverless\user\api\endpoints.go:79
Error on CreateBreakpoint: could not find
D:\PhD\Go\src\serverless\user\api\endpoints.go:81
Error on CreateBreakpoint: could not find
D:\PhD\Go\src\serverless\user\api\endpoints.go:84
All set:[null,null,null,null,null,null]
SetBreakPointsResponse
ConfigurationDoneRequest
ContinueRequest
ContinueResponse
ts=2019-01-01T18:06:57.7842357Z caller=main.go:155 transport=HTTP port=8084

**Comment by ramya-rao-a** [comment]
Are you able to hit the breakpoints when using delve directly from the command line/terminal?
