### ISSUE TITLE
VSCode fails to autocomplete import in _test pacakges

### ISSUE THREAD

**Issue by SteelPhase** [microsoft/vscode-go#2521]
Code Version 1.34.0
VSCode-Go 0.10.2
Go version go1.12.5 darwin/amd64
Gopls commit: b9584148efcb10d08933a70e48b8f7b0732a1b47

When creating a file_test.go file with package `package_test` prevents vscode form being able to autocomplete import package 'package'. This only seems to be the case for a package in the same directory. So my import autocomplete works for everything else.

Example code is below.
for my case import autocomplete should add `github.com/steelphase/example/pkg/example`

```example.go
package example

func Thing() string {
	return "test"
}
```

```example_test.go
package example_test

import "testing"

func TestThing(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := example.Thing(); got != tt.want {
				t.Errorf("Thing() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

**Comment by ramya-rao-a** [comment]
Please share a few more details
- The folder structure for the above case (which file lives where, where is go.mod)
- Which folder is opened in VS Code
- Any Go related settings you might have added/changed
- Any output from the output panel that might be related. `View` -> `Output` -> Select `gopls` or `Go` from the drop down

**Comment by ramya-rao-a** [comment]
Since this is an issue with auto completion when using `gopls`, it is definitely an issue with the language server. 
@stamblerre, @ianthehat  Do you have any insights here?

**Comment by SteelPhase** [comment]
I understand. vscode usually autocompletes the `"example"` import as well, and that's what the core issue is. it appears gopls doesn't consider example as a valid path to import and just doesn't.

**Comment by ramya-rao-a** [comment]
Ah! Looks like this is something that the Go extension is doing independent of `gocode`.

I have pushed a change to do the same even when the language server is being used.
@SteelPhase Can you try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension and see if the issue is resolved?

**Comment by SteelPhase** [comment]
The latest beta does not appear to resolve it.
I just tested on 
Go 0.10.3-beta.4

**Comment by stamblerre** [comment]
@SteelPhase: Are you expecting `gopls` to add the import for you automatically, or are you looking to get autocomplete without having added the import?

**Comment by SteelPhase** [comment]
It adds the import just fine when not using gopls, and when gopls is on it doesn't work.

**Comment by SteelPhase** [comment]
I just wanted to update this, as it's still an issue. My current assumption is that the import path isn't considered in golang.org/x/tools/imports

Additional logs from gopls with imports Debug = true
```log
[Trace - 7:12:01 PM] Sending request 'textDocument/codeAction - (65)'.
Params: {"textDocument":{"uri":"file:///a%3A/Projects/gvs/VanguardAI/pkg/commands/commands_test.go"},"range":{"start":{"line":0,"character":0},"end":{"line":30,"character":0}},"context":{"diagnostics":[{"range":{"start":{"line":18,"character":8},"end":{"line":18,"character":22}},"message":"undeclared name: commanListener","severity":1,"source":"LSP"},{"range":{"start":{"line":24,"character":13},"end":{"line":24,"character":33}},"message":"undeclared name: commands","severity":1,"source":"LSP"}]}}


2019/06/04 19:12:01 fixImports(filename="a:\\Projects\\gvs\\VanguardAI\\pkg\\commands\\commands_test.go"), abs="a:\\Projects\\gvs\\VanguardAI\\pkg\\commands\\commands_test.go", srcDir="a:\\Projects\\gvs\\VanguardAI\\pkg\\commands" ...
2019/06/04 19:12:01 359.6417ms for GOROOT=C:\Go\ GOPATH=A:\Projects\go GO111MODULE= GOPROXY= PWD= go [go env GOMOD]
2019/06/04 19:12:02 334.5236ms for GOROOT=C:\Go\ GOPATH=A:\Projects\go GO111MODULE= GOPROXY= PWD= go [go list -m -json ...]
2019/06/04 19:12:02 module github.com/stretchr/objx has not been downloaded and will be ignored
2019/06/04 19:12:02 322.0358ms for GOROOT=C:\Go\ GOPATH=A:\Projects\go GO111MODULE= GOPROXY= PWD= go [go env GOMOD]
2019/06/04 19:12:03 315.3564ms for GOROOT=C:\Go\ GOPATH=A:\Projects\go GO111MODULE= GOPROXY= PWD= go [go list -m -json ...]
2019/06/04 19:12:03 module github.com/stretchr/objx has not been downloaded and will be ignored
2019/06/04 19:12:03 scanning C:\Go\src
2019/06/04 19:12:03 scanned C:\Go\src
2019/06/04 19:12:03 scanning a:\Projects\gvs\VanguardAI
2019/06/04 19:12:03 scanned a:\Projects\gvs\VanguardAI
2019/06/04 19:12:03 scanning A:\Projects\go\pkg\mod
2019/06/04 19:12:03 Directory added to ignore list: A:\Projects\go\pkg\mod\cache
2019/06/04 19:12:04 scanned A:\Projects\go\pkg\mod
[Trace - 7:12:04 PM] Received response 'textDocument/codeAction - (65)' in 3106ms.
Params: {}


[Trace - 7:12:04 PM] Sending request 'textDocument/formatting - (66)'.
Params: {"textDocument":{"uri":"file:///a%3A/Projects/gvs/VanguardAI/pkg/commands/commands_test.go"},"options":{"tabSize":4,"insertSpaces":false}}


[Trace - 7:12:04 PM] Received response 'textDocument/formatting - (66)' in 1ms.
Params: []
```

**Comment by ramya-rao-a** [comment]
@SteelPhase The fix I was referring to was related to getting completions for `example_test` when you type `package` in the test file. This feature was not working before the latest beta version when using `gopls`. I now see that your issue is much more than that.

@stamblerre Would you agree that this is related to https://github.com/golang/go/issues/29979 and further discussions should be moved there?

**Comment by SteelPhase** [comment]
i was corrected on the gopher slack channel, and it appears they are unrelated.

**Comment by ramya-rao-a** [comment]
Thanks @SteelPhase, closing in favor of the upstream issue https://github.com/golang/go/issues/32440
