### ISSUE TITLE
Language Server strange behaviour

### ISSUE THREAD

**Issue by ignishub** [microsoft/vscode-go#2759]
![image](https://user-images.githubusercontent.com/1565839/65211406-3b40b200-daa7-11e9-875f-ff5345a42373.png)

I just dont even know what to say. Progtramm builded correctly

**Comment by shane-lawrence** [comment]
I have the same issue. It occurs intermittently, and can be resolved temporarily by restarting vscode. In the vscode terminal, $GOPATH is correct, and `go build` and `golint` work without error.
![image](https://user-images.githubusercontent.com/8320787/65212696-33feb180-da71-11e9-90e0-d71ab48ee4b4.png)

**Comment by stamblerre** [comment]
What version of `gopls` is this with (`gopls version`)? This is something I'm aware of and investigating, so for now the best course of action is restarting `gopls`. Do these files belong to packages with in-package tests? I am only familiar with this happening in test files, though it seems like that's not the case in these examples.

**Comment by shane-lawrence** [comment]
Thanks for looking into this. The gopls version is `version v0.1.6-cmd.gopls, built in $GOPATH 
mode`. 

As a workaround, I switched to bingo by adding `"go.alternateTools": {"gopls": "bingo"}` and then Cmd+Shift+P > "Go: Restart Language Server". I'm happy to switch back to gopls and provide more info if it will help.

**Comment by stamblerre** [comment]
`v0.1.7` of `gopls` is out today, and I'd be curious if you're still seeing the same issues with that version. If you'd prefer to stick with bingo, no worries - I can update on this thread when the issue is  resolved.

**Comment by shane-lawrence** [comment]
Updating with `go get golang.org/x/tools/gopls@latest` results in:
```
❯ gopls version
golang.org/x/tools/gopls v0.1.7
    golang.org/x/tools/gopls@v0.1.7 h1:YwKf8t9h69++qCtVmc2q6fVuetFXmmu9LKoPMYLZid4=
```

Note that if I let vscode update gopls ("Go Install/Update Tools") it reverts back to v0.1.6. I switched from bingo back to gopls and I'll run v0.1.7 for a while to see if the issue recurs.

**Comment by stamblerre** [comment]
Thanks for doing this! VSCode-Go downloads `gopls` from master, which is why you're seeing this behavior, but this should be fixed with the latest beta version of the extension.

**Comment by shane-lawrence** [comment]
This issue persists in v0.1.7.

![image](https://user-images.githubusercontent.com/8320787/65215159-87293200-da7a-11e9-88e3-5ff7101ded11.png)

![image](https://user-images.githubusercontent.com/8320787/65214966-d28f1080-da79-11e9-8c8e-79e7407e78e3.png)

**Comment by stamblerre** [comment]
Thanks for confirming. Is this file in a package that also has tests?

**Comment by shane-lawrence** [comment]
Yes.

**Comment by ramya-rao-a** [comment]
@stamblerre Do you have an upstream issue for gopls to track this?

**Comment by stamblerre** [comment]
The upstream issue is now resolved on master. It will be in the next `gopls` release, which should be coming soon.

**Comment by shane-lawrence** [comment]
Great, thanks!

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

Closing this issue in favor of the upstream issue https://github.com/golang/go/issues/34410
