### ISSUE TITLE
Install/Update Tools fails

### ISSUE THREAD

**Issue by SahilMutha** [microsoft/vscode-go#3143]
- go version go1.14.2 windows/amd64
- VSCode 1.43.2
- 0.13.1
- windows amd64

### Share the Go related settings you have added/edited
- No go-related settings in VSCode

### Describe the bug
Description - GO Tools are not installing. Getting "Access Denied Error"
I followed the below thread as well, but did not work for me.
https://github.com/microsoft/vscode-go/issues/2758

Desired output - Should install all the GO Tools

### Steps to reproduce the behavior:
1. Ctrl-Shift-P
2. Go: Install/Update Tools

### Screenshots or recordings
go.toolsGopath setting is not set. Using GOPATH C:\Users\muthas\go
Installing 17 tools at C:\Users\muthas\go\bin in module mode.
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gotests
  gomodifytags
  impl
  fillstruct
  goplay
  godoctor
  dlv
  gocode-gomod
  godef
  goreturns
  golint

Installing github.com/mdempsky/gocode FAILED
Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline FAILED
Installing github.com/acroca/go-symbols FAILED
Installing golang.org/x/tools/cmd/guru FAILED
Installing golang.org/x/tools/cmd/gorename FAILED
Installing github.com/cweill/gotests/... FAILED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl FAILED
Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
Installing github.com/godoctor/godoctor SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv SUCCEEDED
Installing github.com/stamblerre/gocode SUCCEEDED
Installing github.com/rogpeppe/godef FAILED
Installing github.com/sqs/goreturns FAILED
Installing golang.org/x/lint/golint FAILED

10 tools failed to install.

gocode:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/mdempsky/gocode
go: github.com/mdempsky/gocode upgrade => v0.0.0-20200405233807-4acdcbdea79d
go: finding module for package golang.org/x/tools/go/gcexportdata
go: downloading golang.org/x/tools v0.0.0-20200507205054-480da3ebd79c
go: finding module for package golang.org/x/tools/go/gcexportdata
..\..\..\..\..\go\pkg\mod\github.com\mdempsky\gocode@v0.0.0-20200405233807-4acdcbdea79d\internal\cache\importer.go:15:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-787591513 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go: github.com/mdempsky/gocode upgrade => v0.0.0-20200405233807-4acdcbdea79d
go: finding module for package golang.org/x/tools/go/gcexportdata
go: downloading golang.org/x/tools v0.0.0-20200507205054-480da3ebd79c
go: finding module for package golang.org/x/tools/go/gcexportdata
..\..\..\..\..\go\pkg\mod\github.com\mdempsky\gocode@v0.0.0-20200405233807-4acdcbdea79d\internal\cache\importer.go:15:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-787591513 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

go-outline:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/ramya-rao-a/go-outline
go: github.com/ramya-rao-a/go-outline upgrade => v0.0.0-20200117021646-2a048b4510eb
go: finding module for package golang.org/x/tools/go/buildutil
go: finding module for package golang.org/x/tools/go/buildutil
..\..\..\..\..\go\pkg\mod\github.com\ramya-rao-a\go-outline@v0.0.0-20200117021646-2a048b4510eb\main.go:14:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-031931814 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go: github.com/ramya-rao-a/go-outline upgrade => v0.0.0-20200117021646-2a048b4510eb
go: finding module for package golang.org/x/tools/go/buildutil
go: finding module for package golang.org/x/tools/go/buildutil
..\..\..\..\..\go\pkg\mod\github.com\ramya-rao-a\go-outline@v0.0.0-20200117021646-2a048b4510eb\main.go:14:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-031931814 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

go-symbols:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/acroca/go-symbols
go: github.com/acroca/go-symbols upgrade => v0.1.1
go: finding module for package golang.org/x/tools/go/buildutil
go: finding module for package golang.org/x/tools/go/buildutil
..\..\..\..\..\go\pkg\mod\github.com\acroca\go-symbols@v0.1.1\main.go:20:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-038056806 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go: github.com/acroca/go-symbols upgrade => v0.1.1
go: finding module for package golang.org/x/tools/go/buildutil
go: finding module for package golang.org/x/tools/go/buildutil
..\..\..\..\..\go\pkg\mod\github.com\acroca\go-symbols@v0.1.1\main.go:20:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-038056806 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

guru:
Error: Command failed: C:\Go\bin\go.exe get -v golang.org/x/tools/cmd/guru
go get golang.org/x/tools/cmd/guru: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-744989802 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go get golang.org/x/tools/cmd/guru: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-744989802 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

gorename:
Error: Command failed: C:\Go\bin\go.exe get -v golang.org/x/tools/cmd/gorename
go get golang.org/x/tools/cmd/gorename: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-228099722 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go get golang.org/x/tools/cmd/gorename: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-228099722 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

gotests:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/cweill/gotests/...
go: found github.com/cweill/gotests/... in github.com/cweill/gotests v1.5.3
go: finding module for package golang.org/x/tools/imports
go: finding module for package golang.org/x/tools/imports
..\..\..\..\..\go\pkg\mod\github.com\cweill\gotests@v1.5.3\internal\output\output.go:11:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-738612294 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go: found github.com/cweill/gotests/... in github.com/cweill/gotests v1.5.3
go: finding module for package golang.org/x/tools/imports
go: finding module for package golang.org/x/tools/imports
..\..\..\..\..\go\pkg\mod\github.com\cweill\gotests@v1.5.3\internal\output\output.go:11:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-738612294 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

impl:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/josharian/impl
go: github.com/josharian/impl upgrade => v0.0.0-20191119165012-6b9658ad00c7
go: finding module for package golang.org/x/tools/imports
go: finding module for package golang.org/x/tools/imports
..\..\..\..\..\go\pkg\mod\github.com\josharian\impl@v0.0.0-20191119165012-6b9658ad00c7\impl.go:20:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-209283190 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go: github.com/josharian/impl upgrade => v0.0.0-20191119165012-6b9658ad00c7
go: finding module for package golang.org/x/tools/imports
go: finding module for package golang.org/x/tools/imports
..\..\..\..\..\go\pkg\mod\github.com\josharian\impl@v0.0.0-20191119165012-6b9658ad00c7\impl.go:20:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-209283190 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

godef:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/rogpeppe/godef
go: github.com/rogpeppe/godef upgrade => v1.1.2
..\..\..\..\..\go\pkg\mod\github.com\rogpeppe\godef@v1.1.2\packages.go:13:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d.tmp-543543258 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d: Access is denied.
..\..\..\..\..\go\pkg\mod\github.com\rogpeppe\godef@v1.1.2\adapt.go:25:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d.tmp-543543258 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d: Access is denied.
go: github.com/rogpeppe/godef upgrade => v1.1.2
..\..\..\..\..\go\pkg\mod\github.com\rogpeppe\godef@v1.1.2\packages.go:13:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d.tmp-543543258 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d: Access is denied.
..\..\..\..\..\go\pkg\mod\github.com\rogpeppe\godef@v1.1.2\adapt.go:25:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d.tmp-543543258 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200226224502-204d844ad48d: Access is denied.

goreturns:
Error: Command failed: C:\Go\bin\go.exe get -v github.com/sqs/goreturns
go: github.com/sqs/goreturns upgrade => v0.0.0-20181028201513-538ac6014518
go: finding module for package golang.org/x/tools/imports
go: finding module for package golang.org/x/tools/imports
..\..\..\..\..\go\pkg\mod\github.com\sqs\goreturns@v0.0.0-20181028201513-538ac6014518\goreturns.go:21:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-437725530 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.
go: github.com/sqs/goreturns upgrade => v0.0.0-20181028201513-538ac6014518
go: finding module for package golang.org/x/tools/imports
go: finding module for package golang.org/x/tools/imports
..\..\..\..\..\go\pkg\mod\github.com\sqs\goreturns@v0.0.0-20181028201513-538ac6014518\goreturns.go:21:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c.tmp-437725530 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200507205054-480da3ebd79c: Access is denied.

golint:
Error: Command failed: C:\Go\bin\go.exe get -v golang.org/x/lint/golint
go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20200302205851-738671d3881b
..\..\..\..\..\go\pkg\mod\golang.org\x\lint@v0.0.0-20200302205851-738671d3881b\lint.go:26:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7.tmp-599528190 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7: Access is denied.
..\..\..\..\..\go\pkg\mod\golang.org\x\lint@v0.0.0-20200302205851-738671d3881b\lint.go:27:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7.tmp-599528190 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7: Access is denied.
go: found golang.org/x/lint/golint in golang.org/x/lint v0.0.0-20200302205851-738671d3881b
..\..\..\..\..\go\pkg\mod\golang.org\x\lint@v0.0.0-20200302205851-738671d3881b\lint.go:26:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7.tmp-599528190 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7: Access is denied.
..\..\..\..\..\go\pkg\mod\golang.org\x\lint@v0.0.0-20200302205851-738671d3881b\lint.go:27:2: rename C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7.tmp-599528190 C:\Users\muthas\go\pkg\mod\golang.org\x\tools@v0.0.0-20200130002326-2f3ba24bd6e7: Access is denied.

**Comment by hyangah** [comment]
This is probably https://github.com/golang/go/issues/36568.

**Comment by hyangah** [comment]
The latest minor releases (1.14.2 and 1.13.10) include the workaround patch. Please try the updated version of go. (https://golang.org/dl/)

**Comment by cfiderer** [comment]
I also encountered this issue, and it is solved with Go 1.14.2.

**Comment by stamblerre** [comment]
Glad to hear it! I'm going to go ahead and close this issue then. @SahilMutha, please reopen if you're still having this issue with Go 1.14.2.

**Comment by SahilMutha** [comment]
I am still facing this issue with go 1.14.2. I uninstalled go and reinstalled. Do I need to do anything else ?

**Comment by SahilMutha** [comment]
> Glad to hear it! I'm going to go ahead and close this issue then. @SahilMutha, please reopen if you're still having this issue with Go 1.14.2.

I am still facing this issue with go 1.14.2. I uninstalled go and reinstalled. Do I need to do anything else ?

**Comment by hyangah** [comment]
@SahilMutha

**Comment by SahilMutha** [comment]
I have update it in the description now.

**Comment by hyangah** [comment]
@SahilMutha Thanks for the update. According to https://github.com/golang/go/issues/36568#issuecomment-620113685, not all the cls necessary to implement the workaround landed in 1.14.x. They are instead targeting for 1.15. This is unfortunate. How about following this up in [the upstream bug](https://github.com/golang/go/issues/36568)?  

Also make sure to use `GODEBUG=modcacheunzipinplace=1` env var setting and ensure clearing out the module cache (with `go clean -modcache`).

**Comment by ramya-rao-a** [comment]
Closing this issue as there are no next steps from the extension's side.
Please follow up in the upstream issue linked above
