### ISSUE TITLE
[Info] pop ups while writing code in Visual Studio Code

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode-go#50]
_From @andrewrgoss on November 20, 2015 19:22_

Is there a way to turn off the [Info] pop ups that queue up while writing code in VSCode? I have to manually click to close them and I don't want them appearing while writing new code. It's driving me nuts! Tried Googling the topic and couldn't find anything.

<img width="671" alt="vscode_info_popups" src="https://cloud.githubusercontent.com/assets/1461386/11309428/cecb869a-8f91-11e5-96b6-e93aea8fb945.PNG">

_Copied from original issue: Microsoft/vscode#374_

**Comment by lukehoban** [comment]
_From @SamVerschueren on November 20, 2015 20:12_

Have you installed a plugin or something? This isn't core VS Code that's spawning the popups, it's probably a plugin that's not entirely working correctly...

**Comment by lukehoban** [comment]
_From @andrewrgoss on November 20, 2015 20:35_

I installed the Go Support extension before I started using VSCode. Also installed the following Go libraries:

https://github.com/rogpeppe/godef
https://github.com/nsf/gocode
https://github.com/mitchellh/go-ps

First time using VSCode so didn't realize the popups weren't part of the core code. Can you point me to documentation for restoring VSCode default settings?

**Comment by lukehoban** [comment]
_From @bpasero on November 20, 2015 20:56_

@lukehoban fyi

**Comment by lukehoban** [comment]
Yeah - I believe this is a bug in the `vscode-go` plugin.

**Comment by lukehoban** [comment]
@andrewgross Are you seeing this in `.go` files or even in other files?  Do you have an example file that is causing these warnings to pop up?

**Comment by andrewrgoss** [comment]
Seems to be happening only in .go files. I threw together a quick .html file and didn't see any of the pop-ups. 

<html>
	<head>
		<title>Andrewrgoss</title>
	</head>
</html>

However, the pop-ups were piling up when writing this Go code:

// Package stringutil contains utility functions for working with strings.
package stringutil

// Reverse returns its argument string reversed rune-wise left to right.
func Reverse(s string) string {
	r := []rune(s)
	for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
		r[i], r[j] = r[j], r[i]
	}
	return string(r)
}

**Comment by SamVerschueren** [comment]
It's possible to add colors and nice formatting ;).

```go
// Package stringutil contains utility functions for working with strings.
package stringutil

// Reverse returns its argument string reversed rune-wise left to right.
func Reverse(s string) string {
    r := []rune(s)
    for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
        r[i], r[j] = r[j], r[i]
    }
    return string(r)
}
```

**Comment by andrewrgoss** [comment]
Right on! Will use the Markdown syntax moving forward.

```go
// Package stringutil contains utility functions for working with strings.
package stringutil

// Reverse returns its argument string reversed rune-wise left to right.
func Reverse(s string) string {
	r := []rune(s)
	for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
		r[i], r[j] = r[j], r[i]
	}
	return string(r)
}
```

**Comment by lukehoban** [comment]
@andrewrgoss I can't seem to repro with that file standalone. Three more questions:

1) Are you on Windows by any chance?
2) Can you describe what you are doing when these warning appear?  Is it when you hover?  When you type?
3) Are you working in any particular project that you might be able to share a pointer to?

**Comment by lukehoban** [comment]
This should be fixed with 4eb043ea6f8f522f30f10efbe45ca546809610ce which is in the `0.6.10` release.

**Comment by PumpkinSeed** [comment]
I am using the 1.7.1 and still get this very annoying Info pop-ups. Any solution?

**Comment by ramya-rao-a** [comment]
@PumpkinSeed Can you share sample code where you see this?

Are there any errors/warnings showing up in the Problems panel?
When does these pop-ups appear? typing, hovering?

**Comment by PumpkinSeed** [comment]
Not code dependent, it's appearing at .go extensions. Mostly when I am not install GOPATH and GOROOT just want to quickFixes on my Fedora machine. It's rape me with extensions like gofmt, godoc. I don't want to install them just want to fix and save. When I'm typing. 

Thank you

**Comment by xphoniex** [comment]
Same issue here. Very, very, very, VERY, vEry, VeRY, verY annoying !!!!! I think I got my point across.

**Comment by ramya-rao-a** [comment]
There are 2 different kind of pop ups people are talking about here.

1. The one asking you to install Go tools
2. The one that says `Error: Illegal value .. for line`

Now for the first one, I can think of a more friendly way of getting the point across instead of bombarding user with pop ups to install or atleast an option to opt out of it.

For the second, if anyone can provide a consistent repro, then I can look into it.

Can people on this thread reply

**Comment by SR-G** [comment]
Same "problem" here : those popup about installing Go tools are very, very, very annoying. How can they be turned off ? (is there a user preference about this somewhere ?)

**Comment by ramya-rao-a** [comment]
Created #998 to track the replacement of the current pop-up behavior

**Comment by atulkumarpccs** [comment]
Yes, This is due to the extension if you uninstall the extension this kind of warning/error in the status bar will go off.

If need I can provide the screenshot of the steps.

**Comment by ramya-rao-a** [comment]
@atulkumarpccs There are 2 separate kind of notifications talked about in this issue. See https://github.com/Microsoft/vscode-go/issues/50#issuecomment-291559466. Which one are you referring to?

**Comment by atulkumarpccs** [comment]
@ramya-rao-a , I am talking about the issue that when you install extra package and not properly configured then warning will come as you browse the code base.
two solutions here: Either uninstall the extra package or configure it properly.
Comment 50 # It is not clear to me.

**Comment by ramya-rao-a** [comment]
@atulkumarpccs Please elaborate. 
- What do you mean by "extra package"?
- What do you mean by "not properly configured"?
- Is the warning you are see say "Error: Error: Illegal value for `line`"?
