### ISSUE TITLE
go.toolsPath does not resolve ~ or $HOME.

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#784]
I am using a handy extension called "Settings Sync" for vscode that syncs my settings across macOS machines. It works fine, however `go.toolsPath` is a showstopper.

I have different usernames on different machines and I want to install Go tools to `~/gotools` or `$HOME/gotools` but apparently these _shortcuts_ are not resolved before it is passed to go tool:

```
gocode:
Error: Command failed: /usr/local/bin/go get -u -v github.com/nsf/gocode
go: GOPATH entry is relative; must be absolute path: "$HOME/workspace/gotools".
Run 'go help gopath' for usage.
```
or
```
gocode:
Error: Command failed: /usr/local/bin/go get -u -v github.com/nsf/gocode
go: GOPATH entry cannot start with shell metacharacter '~': "~/workspace/gotools"
```

My current solution is to install them under `/tmp`, but I wish there was a more feasible solution supported.

**Comment by ramya-rao-a** [comment]
Nice timing @ahmetalpbalkan! I just implemented ~ https://github.com/Microsoft/vscode-go/commit/ab35627ad3512a958598eea009fa63c7c91ab822

It should be out in the next update which will be early next week

**Comment by ahmetalpbalkan** [comment]
Thanks so much.

**Comment by ahmetb** [comment]
@ramya-rao-a Has there been a release since your patch? I'm still seeing the original behavior.

**Comment by ramya-rao-a** [comment]
I implemented `~` not `$HOME`, which one are you using?

**Comment by ahmetb** [comment]
Got it, I just updated and can confirm ~ works. It's sufficient.

**Comment by ramya-rao-a** [comment]
great
