### ISSUE TITLE
Can't load package. ? i'm not coding a package but a Main Package

### ISSUE THREAD

**Issue by TenshiHitokiri** [Microsoft/vscode-go#910]
Hi, im Having this error but everything works fine, it's annoying and i want to know how to fix it:
'Error' message: 'can't load package: package c:/work/src/primerServer: cannot find package "c:/work/src/primerServer" in any of:
C:\Go\src\c:\work\src\primerServer (from $GOROOT)
c:\work\src\c:\work\src\primerServer (from $GOPATH)

i'm not importing that package, that's my project's and folder's name.
How can i fix it?

**Comment by ramya-rao-a** [comment]
Here is the workaround:

* Uninstall Go extension
* Download the vsix file [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix)
* Run code --install-extension Go-0.5.58.vsix from the location where you downloaded the file

I am trying to understand all different scenarios where this occurs and will publish the fix soon

In your case, I am guessing

- You have opened a Go file under `c:/work/src/primerServer`
- Your GOPATH is `c:/work`. (Run the command `Go: Current GOPATH` to get your GOPATH)

Is that correct? Are you using symlinks ?

**Comment by ramya-rao-a** [comment]
This is fixed in the latest update thats been rolled out 0.6.59

**Comment by Kliton** [comment]
This isn't fixed..  have the 0.6.59 version and still have this error: "file: '
message: 'can't load package: package  -v: cannot find package " -v" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/ -v (from $GOROOT)
	/code/go/src/ -v (from $GOPATH)'

How i can fix this?

**Comment by ramya-rao-a** [comment]
Can you share the build output from your output pane?

**Comment by Kliton** [comment]
Sure. How i can get the build output?

**Comment by Kliton** [comment]
Running tool: /usr/local/bin/go test  -v -timeout 30s -tags 

can't load package: package  -v: cannot find package " -v" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/ -v (from $GOROOT)
	/code/go/src/ -v (from $GOPATH)
Error: Tests failed.

I have MacOs.

**Comment by ramya-rao-a** [comment]
That is the test output, which test command did you run?
For build output select the "Go" channel in the dropdown in the output pane.
Are builds running fine?

**Comment by Kliton** [comment]
`Finished running tool: /code/go/bin/golint

Finished running tool: /usr/local/bin/go tool vet /code/go/src/stampreport/main.go

Finished running tool: /usr/local/bin/go build -o /var/folders/sc/7b8zrdl50tndgslkx5_dl_k00000gn/T/go-code-check -tags ""  -v stampreport
can't load package: package  -v: cannot find package " -v" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/ -v (from $GOROOT)
	/code/go/src/ -v (from $GOPATH)
`

**Comment by ramya-rao-a** [comment]
That is strange, I tried the same set up (having a folder directly under GOPATH/src) and build works for me

<img width="888" alt="screen shot 2017-04-05 at 10 14 51 am" src="https://cloud.githubusercontent.com/assets/16890566/24717878/c65221a8-19e8-11e7-8c31-9d11c81a25e8.png">

Can you run `go build stampreport` on your terminal (opened in the folder stampreport) and see if you get the same error?

**Comment by Kliton** [comment]
No i haven't errors when i run "go build".
I haven't also error when i run debugger.
I have error with "test" and in all files i have errors in package in "problems"
![schermata 2017-04-05 alle 19 25 40](https://cloud.githubusercontent.com/assets/10452377/24718242/ab5bb8ee-1a35-11e7-83b8-4da088749b85.png)

**Comment by ramya-rao-a** [comment]
I am truly stumped.

Looks like you have `-v` as a build flag. Can you try removing that and see if you still get errors?

**Comment by Kliton** [comment]
How i can remove the -v flag?

Because in vscode settings i haven't any flag..

![schermata 2017-04-05 alle 21 54 22](https://cloud.githubusercontent.com/assets/10452377/24724191/88f9001c-1a4a-11e7-8e1a-0e060441eb74.png)

Thanks

**Comment by ramya-rao-a** [comment]
Thats the screenshot of the default settings. We need to check your settings. In the same view, what do you see on the right side?

**Comment by Kliton** [comment]
Oh sorry, my mistake.
I have removed -v flag and now i haven't errors.

Thank you.

**Comment by ramya-rao-a** [comment]
I can repro now as well!

with buildFlags set to `["-v"]` no issues
but if there is an extra space, `[" -v"]`, I get the same error.

Did you have the extra space?
